"""Tests for diff mode functionality."""

import tempfile
from pathlib import Path
from unittest.mock import patch

from click.testing import CliRunner

from uv_workspace_codegen.main import main


def _make_workspace(workspace_dir: Path, package_dir: Path) -> None:
    """Create a minimal valid UV workspace with one package."""
    with open(workspace_dir / "pyproject.toml", "w") as f:
        f.write(f"""
[tool.uv.workspace]
members = ["{package_dir.relative_to(workspace_dir)}"]
""")


def test_diff_mode_new_file():
    """Test diff mode with a new file (should show addition)."""
    runner = CliRunner()
    with tempfile.TemporaryDirectory() as temp_dir:
        workspace_dir = Path(temp_dir)

        package_dir = workspace_dir / "my-package"
        package_dir.mkdir()

        with open(package_dir / "pyproject.toml", "w") as f:
            f.write("""
[project]
name = "my-package"
version = "0.1.0"

[tool.uv-workspace-codegen]
generate = true
template_type = "package"
generate_standard_pytest_step = true
""")

        _make_workspace(workspace_dir, package_dir)

        with patch(
            "uv_workspace_codegen.main.find_workspace_root", return_value=workspace_dir
        ):
            result = runner.invoke(main, ["--diff"])

        assert result.exit_code == 0, result.output
        assert "--- " in result.output
        assert "+++ " in result.output
        assert (
            "+# This file was automatically generated by uv-workspace-codegen"
            in result.output
        )

        workflow_path = (
            workspace_dir / ".github" / "workflows" / "package-my-package.yml"
        )
        assert not workflow_path.exists()


def test_diff_mode_modified_file():
    """Test diff mode with a modified file."""
    runner = CliRunner()
    with tempfile.TemporaryDirectory() as temp_dir:
        workspace_dir = Path(temp_dir)

        package_dir = workspace_dir / "my-package"
        package_dir.mkdir()

        with open(package_dir / "pyproject.toml", "w") as f:
            f.write("""
[project]
name = "my-package"
version = "0.1.0"

[tool.uv-workspace-codegen]
generate = true
template_type = "package"
generate_standard_pytest_step = true
""")

        _make_workspace(workspace_dir, package_dir)

        workflows_dir = workspace_dir / ".github" / "workflows"
        workflows_dir.mkdir(parents=True)
        workflow_path = workflows_dir / "package-my-package.yml"

        with open(workflow_path, "w") as f:
            f.write("# Old content\nname: Old Workflow\n")

        with patch(
            "uv_workspace_codegen.main.find_workspace_root", return_value=workspace_dir
        ):
            result = runner.invoke(main, ["--diff"])

        assert result.exit_code == 0, result.output
        assert "--- " in result.output
        assert "+++ " in result.output
        assert "-# Old content" in result.output
        assert (
            "+# This file was automatically generated by uv-workspace-codegen"
            in result.output
        )

        with open(workflow_path, "r") as f:
            content = f.read()
        assert content == "# Old content\nname: Old Workflow\n"


def test_diff_mode_no_changes():
    """Test diff mode with no changes."""
    runner = CliRunner()
    with tempfile.TemporaryDirectory() as temp_dir:
        workspace_dir = Path(temp_dir)

        package_dir = workspace_dir / "my-package"
        package_dir.mkdir()

        with open(package_dir / "pyproject.toml", "w") as f:
            f.write("""
[project]
name = "my-package"
version = "0.1.0"

[tool.uv-workspace-codegen]
generate = true
template_type = "package"
generate_standard_pytest_step = true
""")

        _make_workspace(workspace_dir, package_dir)

        with patch(
            "uv_workspace_codegen.main.find_workspace_root", return_value=workspace_dir
        ):
            runner.invoke(main, [])

        with patch(
            "uv_workspace_codegen.main.find_workspace_root", return_value=workspace_dir
        ):
            result = runner.invoke(main, ["--diff"])

        assert result.exit_code == 0, result.output
        assert "--- " not in result.output
        assert "+++ " not in result.output


def test_diff_mode_stale_file():
    """Test diff mode with a stale file (should not delete, but report)."""
    runner = CliRunner()
    with tempfile.TemporaryDirectory() as temp_dir:
        workspace_dir = Path(temp_dir)

        package_dir = workspace_dir / "my-package"
        package_dir.mkdir()

        with open(package_dir / "pyproject.toml", "w") as f:
            f.write("""
[project]
name = "my-package"
version = "0.1.0"

[tool.uv-workspace-codegen]
generate = true
template_type = "package"
generate_standard_pytest_step = true
""")

        _make_workspace(workspace_dir, package_dir)

        workflows_dir = workspace_dir / ".github" / "workflows"
        workflows_dir.mkdir(parents=True)
        stale_workflow_path = workflows_dir / "stale-workflow.yml"

        with open(stale_workflow_path, "w") as f:
            f.write(
                "# This file was automatically generated by uv-workspace-codegen\nname: Stale\n"
            )

        with patch(
            "uv_workspace_codegen.main.find_workspace_root", return_value=workspace_dir
        ):
            result = runner.invoke(main, ["--diff"])

        assert result.exit_code == 0, result.output
        assert stale_workflow_path.exists()
        assert f"Would remove stale workflow: {stale_workflow_path}" in result.output


def test_diff_mode_valid_file():
    """Test diff mode with a valid file (should not report as stale)."""
    runner = CliRunner()
    with tempfile.TemporaryDirectory() as temp_dir:
        workspace_dir = Path(temp_dir)

        package_dir = workspace_dir / "my-package"
        package_dir.mkdir()

        with open(package_dir / "pyproject.toml", "w") as f:
            f.write("""
[project]
name = "my-package"
version = "0.1.0"

[tool.uv-workspace-codegen]
generate = true
template_type = "package"
generate_standard_pytest_step = true
""")

        _make_workspace(workspace_dir, package_dir)

        with patch(
            "uv_workspace_codegen.main.find_workspace_root", return_value=workspace_dir
        ):
            runner.invoke(main, [])

        with patch(
            "uv_workspace_codegen.main.find_workspace_root", return_value=workspace_dir
        ):
            result = runner.invoke(main, ["--diff"])

        assert result.exit_code == 0, result.output
        assert "Would remove stale workflow" not in result.output
